### ISSUE TITLE
Having trouble with the git pull

### ISSUE THREAD

**Issue by JennyDonnelly** [ga-students/DAT-NYC-29#1]
Git registering in cygwin terminal; trying to use command to git pull copied URL hw file and not working. any ideas?

**Comment by jmwitten** [comment]
can you paste what you typed and what the output was? you should just do "git pull" without any urls

**Comment by JennyDonnelly** [comment]
git pull DAT-NYC-29/Homework/HW1/Debugging Homework.ipynb

**Comment by jmwitten** [comment]
just do git pull

**Comment by jmwitten** [comment]
@JennyDonnelly Did that work?
